# This is a basic workflow that is manually triggered

name: Wordle ErryDay

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: "Manually Tweet Wordle"
        required: false

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - id: solver
        run: node ${{ github.workspace }}/index.js >> status.md
      
      - name: "Can use environment variables"
        run: cat status.md
     
      - name: Send Tweet Action
        uses: ethomson/send-tweet-action@v1.0.0
        with:
          status: $(cat status.md)
          consumer-key: ${{secrets.TWITTER_API_KEY}}
          consumer-secret: ${{secrets.TWITTER_API_KEY_SECRET}}
          access-token: ${{secrets.TWITTER_ACCESS_TOKEN}}
          access-token-secret: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
