# This is a basic workflow that is manually triggered

name: Wordle ErryDay

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    schedule:
      cron: 0 0 * * *
    # Inputs the workflow accepts.
    inputs:
      name:
        description: "Manually Tweet Wordle"
        required: false

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: node ${{ github.workspace }}/index.js
