# This is a basic workflow that is manually triggered

name: Wordle ErryDay

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: "Manually Tweet Wordle"
        required: false

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - id: solver
        run: |
          echo "::set-output name=STAT_US::$(node ${{ github.workspace }}/index.js)"
      
      - name: "Can use environment variables"
        run: |
          echo ${{ steps.solver.outputs.STAT_US }}
  #       # You may pin to the exact commit or the version.
  #      # uses: ethomson/send-tweet-action@288f9339e0412e3038dce350e0da5ecdf12133a6
  #     uses: ethomson/send-tweet-action@v1.0.0
  #    with:
  #     # The status ("tweet") to post to twitter.
  #    status: "Wordle..."
  #   # Consumer API key, available in the "Keys and tokens" section of your application in the Twitter Developer site.

#      - name: Send Tweet Action
#
#         consumer-key: ${{secrets.TWITTER_API_KEY}}
#        # Consumer API secret key, available in the "Keys and tokens" section of your application in the Twitter Developer site.
#
#         consumer-secret: ${{secrets.TWITTER_API_KEY_SECRET}}
#        # Application access token, available in the "Keys and tokens" section of your application in the Twitter Developer site.
#
#         access-token: ${{secrets.TWITTER_ACCESS_TOKEN}}
#        # Application access token secret, available in the "Keys and tokens" section of your application in the Twitter Developer site.
#
#         access-token-secret: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
